### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Gibt die Anzahl der derzeit zur Verfügung stehenden Qubits zurück. Dies schließt nicht verwendete Qubits ein. Das heißt, dies schließt die von zurückgegebenen Qubits ein `GetQubitsAvailableToUse` .
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Gibt die Anzahl der zurzeit verfügbaren Qubits zurück.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Diese Funktionen stellen Informationen über die Umgebung bereit, in der die Quantum-Berechnung auftritt.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 04a3ffe56be7da2c9adc13e2b27fe9ce0f982c44
  ms.sourcegitcommit: 29e0d88a30e4166fa580132124b0eb57e1f0e986
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 10/27/2020
  ms.locfileid: "92702845"
