### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Gibt die Anzahl der derzeit zur Verfügung stehenden Qubits zurück.

  Dies schließt nicht verwendete Qubits ein. Das heißt, dies schließt die Qubits ein, die von `GetQubitsAvailableToUse`zurückgegeben werden.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Die Anzahl der Qubits, die in einer `borrowing` Anweisung zugeordnet werden können.

      Wenn der verwendete Zielcomputer diese Informationen nicht bereitstellt, wird `-1` zurückgegeben.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230482"
