### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Zusammenfassung\n Diese Funktionen stellen Informationen über die Umgebung bereit, in der die Quantum-Berechnung auftritt."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Gibt die Anzahl der derzeit zur Verfügung stehenden Qubits zurück.

    Dies schließt nicht verwendete Qubits ein. Das heißt, dies schließt die von zurückgegebenen Qubits ein `GetQubitsAvailableToUse` .
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Gibt die Anzahl der zurzeit verfügbaren Qubits zurück.
metadata:
  ms.openlocfilehash: 7f597d8f429089b0ebf2c22cef1d1b98ea270402
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89341155"
