### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Zusammenfassung\n Diese Funktionen stellen Informationen über die Umgebung bereit, in der die Quantum-Berechnung auftritt."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Gibt die Anzahl der derzeit zur Verfügung stehenden Qubits zurück.

    Dies schließt nicht verwendete Qubits ein. Das heißt, dies schließt die von `GetQubitsAvailableToUse`zurückgegebenen Qubits ein.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Gibt die Anzahl der zurzeit verfügbaren Qubits zurück.
metadata:
  ms.openlocfilehash: bd6d442aabb179f4c5fea0a0f48efaa472ec00cf
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82673350"
